name: Build & Test It Depends on all platforms
on:
  push:
    branches:
      - "main"
      - "*"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            generator: Ninja
            test_command: ./bin/id_tests

          - os: macos-latest
            generator: Ninja
            test_command: ./bin/id_tests

          - os: windows-latest
            generator: Ninja
            test_command: '.\bin\id_tests.exe'

    runs-on: ${{matrix.os}}
    steps:
      - name: Install Windows dependencies
        if: contains(matrix.os, 'windows')
        uses: msys2/setup-msys2@v2
        with:
          location: ${{env.msys}}
          msystem: mingw64
          install: mingw-w64-x86_64-ninja

      - name: Install MacOS dependencies
        if: contains(matrix.os, 'macos')
        run: brew install ninja

      - name: Install Linux dependencies
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt install -y cmake ninja-build

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
          arch: win64_msvc2019_64

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create It Depends project
        run: cmake . -G "${{matrix.generator}}" -Duse_qt6=true -DCMAKE_CXX_FLAGS='-w'

      - name: Build It Depends
        run: ninja ItDepends

      - name: Build It Depends tests
        run: ninja id_tests

      - name: Execute It Depends tests
        run: ${{matrix.test_command}}
