name: Build & Test It Depends on all platforms
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

env:
  BOOST_VERSION: 1.71.0
  BOOST_PATH: ${{github.workspace}}/boost/boost

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            generator: Ninja
            test_command: ./bin/id_tests

          - os: macos-latest
            generator: Ninja
            test_command: ./bin/id_tests

          - os: windows-latest
            generator: Ninja
            test_command: '& bin/id_tests.exe'

    runs-on: ${{matrix.os}}
    steps:
      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          location: ${{env.msys}}
          msystem: mingw64
          install: mingw-w64-x86_64-ninja

      - name: Install MacOS dependencies
        if: matrix.os == 'macos-latest'
        run: brew install ninja

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install -y cmake ninja-build

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          arch: win64_mingw81

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create It Depends project
        run: |
          cmake . -G "${{matrix.generator}}" \
          -Dpackaging=true \
          -DCMAKE_CXX_FLAGS='-w'

      - name: Build It Depends
        run: ninja itdepends

      - name: Build It Depends tests
        run: ninja id_tests

      - name: Execute It Depends tests
        run: ${{matrix.test_command}}
