name: Build & Test It Depends on all platforms
on:
  push:
    branches:
      - "main"
      - "*"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            test_command: ./bin/id_tests
            qt_arch: gcc_64

          - os: macos-13
            test_command: ./bin/id_tests
            qt_arch: clang_64

          - os: windows-latest
            test_command: '.\bin\id_tests.exe'
            qt_arch: win64_mingw

    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Windows dependencies
        if: contains(matrix.os, 'windows')
        uses: msys2/setup-msys2@v2
        with:
          location: ${{ env.msys }}
          msystem: mingw64
          install: mingw-w64-x86_64-ninja

      - name: Install MacOS dependencies
        if: contains(matrix.os, 'macos')
        run: brew install ninja

      - name: Install Linux dependencies
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt install -y cmake ninja-build

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.2'
          arch: ${{ matrix.qt_arch }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create It Depends project
        run: cmake . -G Ninja -DCMAKE_CXX_FLAGS='-w' -Dgenerate_coverage_report=true

      - name: Build It Depends
        run: ninja ItDepends

      - name: Build It Depends tests
        run: ninja id_tests

      - name: Execute It Depends tests
        run: ${{ matrix.test_command }}

      - name: Upload coverage reports to Codecov
        if: contains(matrix.os, 'ubuntu')
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
