name: Package It Depends for all platforms
on:
  push:
    tags:
      - v*

jobs:
  package:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            generator: Ninja
            artifact_name: ItDepends_x64-Linux.tar.gz
            qt_arch: gcc_64

          - os: macos-latest
            generator: Ninja
            artifact_name: ItDepends_x64-MacOS.zip
            qt_arch: clang_64

          - os: windows-latest
            generator: Ninja
            artifact_name: ItDepends_x64-MacOS.zip
            qt_arch: win64_mingw

    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Windows dependencies
        if: contains(matrix.os, 'windows')
        uses: msys2/setup-msys2@v2
        with:
          location: ${{env.msys}}
          msystem: mingw64
          install: mingw-w64-x86_64-ninja

      - name: Install MacOS dependencies
        if: contains(matrix.os, 'macos')
        run: brew install ninja

      - name: Install Linux dependencies
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt install -y cmake ninja-build

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
          arch: '${{matrix.qt_arch}}'

      - name: Create It Depends project
        run: |
          cmake . -G "${{matrix.generator}}" -Dpackaging=true -DCMAKE_CXX_FLAGS='-w'

      - name: Build It Depends
        run: ninja ItDepends

      - name: Zip the Windows executable
        if: contains(matrix.os, 'windows')
        run: |
          7z a -tzip ${{matrix.artifact_name}} ./bin/ItDepends.exe

      - name: Zip the MacOS bundle
        if: contains(matrix.os, 'macos')
        run: |
          zip -rT ${{matrix.artifact_name}} ./bin/ItDepends.app >> /dev/null

      - name: Create or update Release with artifacts
        uses: ncipollo/release-action@v1.12.0
        if: ${{ !contains(matrix.os, 'ubuntu') }}
        with:
          allowUpdates: true
          generateReleaseNotes: true
          makeLatest: true
          name: ${{ github.ref }}
          artifact: ${{ matrix.artifact_name }}
          artifactContentType: application/zip
